Petopia/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from PetopiaApp.views import SignUpView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('PetopiaApp.urls', namespace='PetopiaApp')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PetopiaApp/urls.py
from django.urls import path
from PetopiaApp.views import home, add_pet_category, shopping_cart, add_to_cart, \
    remove_from_cart, product, remove_one_item_from_cart, checkout, add_product, payment, orders
from django.conf import settings
from django.conf.urls.static import static

app_name = 'PetopiaApp'

urlpatterns = [
    path("", home, name='home'),
    path("<category>", home, name='home'),

    path("add-pet-category/", add_pet_category, name='add_pet_category'),
    path("add-product/", add_product, name='add_product'),

    path('product/<name>/<slug>', product, name='product'),

    path('cart/shopping-cart', shopping_cart, name='shopping_cart'),
    path('add-to-cart/<slug>', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug>', remove_from_cart, name='remove_from_cart'),
    path('remove-one-item-from-cart/<slug>', remove_one_item_from_cart, name='remove_one_item_from_cart'),

    path('checkout/', checkout, name='checkout'),
    path('payment/<payment_option>', payment, name='payment'),
    path('orders/', orders, name='orders')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PetopiaApp/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User

# Create your models here.

PRODUCT_CATEGORIES = (
    ('food', 'food'),
    ('hygiene', 'hygiene'),
    ('toys', 'toys'),
    ('transport', 'transport')
)


class PetCategory(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to="images/pet_images/", null=True, blank=True)

    def __str__(self):
        return f"{self.name}"


class Brand(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    image = models.ImageField(upload_to="images/product_images/", null=True)
    short_description = models.CharField(max_length=255)
    detailed_description = models.TextField()
    pet_category = models.ForeignKey(PetCategory, on_delete=models.CASCADE)
    product_category = models.CharField(max_length=10, choices=PRODUCT_CATEGORIES)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    slug = models.SlugField()

    def __str__(self):
        return f"{self.name} - ${self.price}"

    def get_absolute_url(self):
        return reverse("PetopiaApp:product", kwargs={
            'slug': self.slug,
            'name': self.pet_category
        })


class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} x {self.product}"

    def get_total_cart_item_price(self):
        return self.quantity * self.product.price


class ShoppingCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(CartItem)

    def __str__(self):
        return f"{self.user.username}"

    def get_total(self):
        total = 0
        for cart_item in self.items.all():
            total += cart_item.get_total_cart_item_price()
        return total

    def get_total_num_items(self):
        total = 0
        for cart_item in self.items.all():
            total += cart_item.quantity
        return total

PetopiaApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from PetopiaApp.models import PetCategory, Product
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


class PetCategoryForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(PetCategoryForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = PetCategory
        fields = ["name", ]


class ProductForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Product
        fields = ["name", "price", "image", "short_description", "detailed_description", "pet_category",
                  "product_category", "brand", "slug"]


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)


class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': '1234 Main St'
    }))
    apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Apartment or suite'
    }))
    country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(
        attrs={'class': 'custom-select d-block w-100'})
    )
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    same_shipping_address = forms.BooleanField(required=False)
    save_info = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

PetopiaApp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404

from PetopiaApp.filters import ProductFilter
from PetopiaApp.forms import PetCategoryForm, CheckoutForm, ProductForm
from PetopiaApp.models import Product, PetCategory, ShoppingCart, CartItem
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.utils import timezone
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.db.models import Q


# Create your views here.

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


def home(request, category=None):
    all_products = Product.objects.all()
    search_query = request.GET.get('search_query')
    if category is not None and request.GET.get('search_query') is None:
        all_products = Product.objects.filter(pet_category=category).all()
    elif (category is None or category is not None) and request.GET.get('search_query') is not None:
        all_products = Product.objects.filter(Q(name__icontains=search_query) |
                                              Q(short_description__icontains=search_query)).all()

    pet_categories = PetCategory.objects.all()
    filter_form = ProductFilter(request.GET, queryset=all_products)

    p = Paginator(all_products, 8)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)

    all_products = page_obj

    context = {'products': all_products, 'pet_categories': pet_categories, 'filter': filter_form}
    return render(request, "home.html", context)


@login_required(login_url="/accounts/login/?next=/")
def add_pet_category(request):
    if request.method == "POST":
        form_data = PetCategoryForm(data=request.POST, files=request.FILES)
        if form_data.is_valid():
            pet_category = form_data.save(commit=False)
            pet_category.save()
            return redirect("PetopiaApp:home")
    return render(request, "admin-actions/add_pet_category.html", context={"form": PetCategoryForm})


@login_required(login_url="/accounts/login/?next=/")
def add_product(request):
    if request.method == "POST":
        form_data = ProductForm(data=request.POST, files=request.FILES)
        if form_data.is_valid():
            print('form data is valid')
            product_obj = form_data.save(commit=False)
            product_obj.name = form_data.cleaned_data.get('name')
            product_obj.price = form_data.cleaned_data.get('price')
            product_obj.image = form_data.cleaned_data.get('image')
            product_obj.short_description = form_data.cleaned_data.get('short_description')
            product_obj.detailed_description = form_data.cleaned_data.get('detailed_description')
            product_obj.pet_category = form_data.cleaned_data.get('pet_category')
            product_obj.product_category = form_data.cleaned_data.get('product_category')
            product_obj.brand = form_data.cleaned_data.get('brand')
            product_obj.slug = form_data.cleaned_data.get('slug')
            product_obj.save()
            return redirect("PetopiaApp:home")
    return render(request, "admin-actions/add_product.html", context={"form": ProductForm})


def product(request, name, slug):
    product_object = Product.objects.filter(slug=slug)[0]
    context = {'object': product_object, 'pet_category': name}
    return render(request, "product.html", context)


@login_required(login_url="/accounts/login/?next=/")
def shopping_cart(request):
    try:
        cart = ShoppingCart.objects.get(user=request.user, ordered=False)
    except ObjectDoesNotExist:
        date_ordered = timezone.now()
        cart = ShoppingCart.objects.create(user=request.user, date_ordered=date_ordered)
    context = {'object': cart}
    return render(request, "cart/shopping_cart.html", context)


@login_required(login_url="/accounts/login/?next=/")
def add_to_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    cart_item, created = CartItem.objects.get_or_create(
        product=product,
        user=request.user,
        ordered=False)
    cart_qs = ShoppingCart.objects.filter(user=request.user, ordered=False)
    if cart_qs.exists():
        cart = cart_qs[0]
        if cart.items.filter(product__slug=product.slug).exists():
            cart_item.quantity += 1
            cart_item.save()
            messages.info(request, "The item quantity was increased!")
            return redirect("PetopiaApp:shopping_cart")
        else:
            messages.info(request, "This item was added to your cart!")
            cart.items.add(cart_item)
            return redirect("PetopiaApp:shopping_cart")
    else:
        date_ordered = timezone.now()
        cart = ShoppingCart.objects.create(user=request.user, date_ordered=date_ordered)
        cart.items.add(cart_item)
        messages.info(request, "This item was added to your cart!")
        return redirect("PetopiaApp:shopping_cart")


@login_required(login_url="/accounts/login/?next=/")
def remove_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = ShoppingCart.objects.filter(
        user=request.user,
        ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(product__slug=product.slug).exists():
            order_item = CartItem.objects.filter(
                product=product,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            messages.info(request, "The item was removed from your cart!")
            return redirect("PetopiaApp:shopping_cart")
        else:
            messages.info(request, "This item was not in your cart!")
            return redirect("PetopiaApp:product", slug=slug)
    else:
        messages.info(request, "You do not have an active shopping cart.")
        return redirect("PetopiaApp:product", slug=slug)


@login_required(login_url="/accounts/login/?next=/")
def remove_one_item_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = ShoppingCart.objects.filter(
        user=request.user,
        ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(product__slug=product.slug).exists():
            order_item = CartItem.objects.filter(
                product=product,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "The item quantity was decreased.")
            return redirect("PetopiaApp:shopping_cart")
        else:
            messages.info(request, "This item was not in your cart!")
            return redirect("PetopiaApp:product", slug=slug)
    else:
        messages.info(request, "You do not have an active shopping cart.")
        return redirect("PetopiaApp:product", slug=slug)


@login_required(login_url="/accounts/login/?next=/")
def checkout(request):
    if request.method == 'GET':
        form = CheckoutForm()
        cart = ShoppingCart.objects.get(user=request.user, ordered=False)
        context = {'form': form, 'object': cart}
        return render(request, 'cart/checkout.html', context)
    if request.method == "POST":
        form = CheckoutForm(data=request.POST)
        try:
            cart = ShoppingCart.objects.get(user=request.user, ordered=False)
            if form.is_valid():
                payment_option = form.cleaned_data.get('payment_option')
                cart.save()
                if payment_option == 'S':
                    return redirect('PetopiaApp:payment', payment_option='stripe')
                elif payment_option == 'P':
                    return redirect('PetopiaApp:payment', payment_option='paypal')
            else:
                messages.warning(request, "Failed Checkout")
                return render(request, 'cart/checkout.html', {'form': form})
        except ObjectDoesNotExist:
            messages.error(request, "You do not have an active shopping cart!")
            return redirect("PetopiaApp:shopping_cart")


@login_required(login_url="/accounts/login/?next=/")
def payment(request, payment_option):
    if request.method == "GET":
        cart = ShoppingCart.objects.get(user=request.user, ordered=False)
        context = {'payment_option': payment_option, 'object': cart}
        return render(request, "cart/payment.html", context)
    if request.method == "POST":
        cart = ShoppingCart.objects.get(user=request.user, ordered=False)
        cart.ordered = True
        cart.date_ordered = timezone.now()
        cart.save()
        messages.success(request, "Your order was successful!")
        return redirect("PetopiaApp:home")


@login_required(login_url="/accounts/login/?next=/")
def orders(request):
    query = ShoppingCart.objects.filter(user=request.user, ordered=True)
    context = {'orders': query}
    return render(request, "cart/orders.html", context)

PetopiaApp/templates/home.html
{% extends "base.html" %}
{% block content %}

    <main>
        <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">

            <ol class="carousel-indicators">
                <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-1z" data-slide-to="1"></li>
                <li data-target="#carousel-example-1z" data-slide-to="2"></li>
            </ol>

            <div class="carousel-inner" role="listbox">

                <div class="carousel-item active">
                    <div class="view"
                         style="background-image: url('https://th.bing.com/th/id/R.ee2bccd2697756832c7a627f1fed08ae?rik=Hiaaqu4AVhpqdw&riu=http%3a%2f%2fechopetcare.com%2fwp-content%2fuploads%2f2017%2f05%2fcropped-pets-banner.jpg&ehk=18Pvd%2bPIyDUraGWSV0LYUJzF6E7hKTIpPY6Hqhc1OXw%3d&risl=&pid=ImgRaw&r=0'); background-repeat: no-repeat; background-size: cover;">

                        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

                            <div class="text-center white-text mx-5 wow fadeIn">
                                <h1 class="mb-4">
                                    <strong>Shop the best supplies for your pet</strong>
                                </h1>

                                <p>
                                    <strong>Quality products delivered to your door</strong>
                                </p>

                                <p class="mb-4 d-none d-md-block">
                                    <strong>We supply products for food, hygiene, carriers for transportation, healthy
                                        snacks, toys and more! Check out the different categories below.</strong>
                                </p>

                                <a href="#categories" class="btn btn-outline-white btn-lg">
                                    BROWSE PRODUCTS
                                    <i class="fas fa-light fa-paw ml-2"></i>
                                </a>
                            </div>

                        </div>

                    </div>
                </div>

                <div class="carousel-item">
                    <div class="view"
                         style="background-image: url('https://www.fetchpetcare.com/wp-content/uploads/2016/03/Dogs-Afraid-of-Cats-Featured-e1459436099821.jpg'); background-repeat: no-repeat; background-size: cover;">

                        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

                            <div class="text-center white-text mx-5 wow fadeIn">
                                <h1 class="mb-4">
                                    <strong>Shop the best supplies for your pet</strong>
                                </h1>

                                <p>
                                    <strong>Quality products delivered to your door</strong>
                                </p>

                                <p class="mb-4 d-none d-md-block">
                                    <strong>We supply products for food, hygiene, carriers for transportation, healthy
                                        snacks, toys and more! Check out the different categories below.</strong>
                                </p>

                                <a href="#categories" class="btn btn-outline-white btn-lg">
                                    BROWSE PRODUCTS
                                    <i class="fas fa-light fa-paw ml-2"></i>
                                </a>
                            </div>

                        </div>

                    </div>
                </div>

                <div class="carousel-item">
                    <div class="view"
                         style="background-image: url('https://st3.depositphotos.com/1032808/14072/i/450/depositphotos_140726578-stock-photo-kitten-puppy-microscope.jpg'); background-repeat: no-repeat; background-size: cover;">

                        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

                            <div class="text-center white-text mx-5 wow fadeIn">
                                <h1 class="mb-4">
                                    <strong>Shop the best supplies for your pet</strong>
                                </h1>

                                <p>
                                    <strong>Quality products delivered to your door</strong>
                                </p>

                                <p class="mb-4 d-none d-md-block">
                                    <strong>We supply products for food, hygiene, carriers for transportation, healthy
                                        snacks, toys and more! Check out the different categories below.
                                    </strong>

                                </p>

                                <a href="#categories" class="btn btn-outline-white btn-lg">
                                    Browse Products
                                    <i class="fas fa-light fa-paw ml-2"></i>
                                </a>
                            </div>

                        </div>

                    </div>
                </div>

            </div>

            <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>

        </div>

        <main>
            <div class="container">


                <nav class="navbar navbar-expand-lg text-dark navbar-dark lighten-3 mt-3 mb-5"
                     style="background-color: #DBAE6E">


                    <span class="navbar-brand" id="categories">Categories:</span>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                            aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="basicExampleNav">

                        <ul class="navbar-nav mr-auto parent">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'PetopiaApp:home' %}">All
                                    <span class="sr-only">(current)</span>
                                </a>
                            </li>
                            {% for category in pet_categories %}
                                <li class="nav-item">
                                    <a class="nav-link"
                                       href="{% url 'PetopiaApp:home' category.id %}">{{ category.name.capitalize }}</a>
                                </li>
                            {% endfor %}
                        </ul>

                        <form class="form-inline" action="{% url 'PetopiaApp:home' %}" method="GET">

                            <div class="md-form my-0">
                                <input class="form-control mr-sm-2" type="text" name="search_query" placeholder="Search"
                                       aria-label="Search">
                            </div>
                            <button class="btn" type="submit" title="Search">
                                <i class="fas fa-search text-white"></i>
                            </button>
                        </form>

                    </div>

                </nav>

                <section class="text-center mb-4">
                    <div class="row wow fadeIn">

                        {% for item in products %}
                            <div class="col-lg-3 col-md-6 mb-4">

                                <div class="card" style="height: 360px">

                                    <div class="view overlay">
                                        <img src="{{ MEDIA_URL }}{{ item.image.url }}" class="card-img-top img-fluid"
                                             alt="">

                                        <a href="{{ item.get_absolute_url }}">
                                            <div class="mask rgba-white-slight"></div>
                                        </a>
                                    </div>

                                    <div class="card-body text-center">
                                        <a href="" class="grey-text">
                                            <h5>{{ item.get_category_display }}</h5>
                                        </a>

                                        <h5>
                                            <strong>
                                                <a href="{{ item.get_absolute_url }}"
                                                   class="dark-grey-text">{{ item.name }}</a>
                                            </strong>
                                        </h5>

                                        <p class="text-muted">
                                            {{ item.short_description }}
                                        </p>

                                        <h4 class="font-weight-bold blue-text">
                                            <strong class="text-danger">$
                                                {% if item.discount_price %}
                                                    {{ item.discount_price }}
                                                {% else %}
                                                    {{ item.price }}
                                                {% endif %}
                                            </strong>
                                        </h4>

                                    </div>

                                </div>

                            </div>
                        {% endfor %}
                    </div>

                    {% if request.user.is_superuser %}
                        <div class="row m-2 d-flex justify-content-center text-white">
                            <a class="btn btn-md col-3" style="background-color: #0A3E09"
                               href="{% url 'PetopiaApp:add_pet_category' %}">Add new pet category</a>
                            <a class="btn btn-md col-3" style="background-color: #0A3E09"
                               href="{% url 'PetopiaApp:add_product' %}">Add new product</a>
                        </div>
                    {% endif %}

                </section>


                <nav class="d-flex justify-content-center wow fadeIn">
                    <ul class="pagination">

                        {% if products.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ products.previous_page_number }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link"
                                   href="?page={{ products.previous_page_number }}">{{ products.previous_page_number }}
                                    <span class="sr-only">{{ products.previous_page_number }}</span>
                                </a>
                            </li>
                        {% endif %}

                        <li class="page-item" style="background-color: #DBAE6E">
                            <a class="page-link" href="#">{{ products.number }}
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>

                        {% if products.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="?page={{ products.next_page_number }}">{{ products.next_page_number }}</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>

            </div>
        </main>

    </main>
{% endblock content %}

PetopiaApp/templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar navbar-expand-lg navbar-light scrolling-navbar" style="background-color: #DBAE6E;">
    <div class="container">

        <a class="navbar-brand waves-effect" href="/">
            <strong class="display-4">PETOPIA</strong>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav mr-auto">
            </ul>

            <ul class="navbar-nav nav-flex-icons pr-5">
                {% if request.user.is_authenticated %}

                    <li class="nav-item">
                        <span class="text-dark nav-link waves-effect">
                            <span class="clearfix d-none d-sm-inline-block">Hello {{ request.user.username }}!</span>
                        </span>
                    </li>

                    <li class="nav-item">
                        <a class="text-dark nav-link waves-effect" href="{% url 'PetopiaApp:orders' %}">
                            <span class="clearfix d-none d-sm-inline-block">Orders</span>
                        </a>
                    </li>


                    <li class="nav-item">
                        <a href="{% url 'PetopiaApp:shopping_cart' %}" class="nav-link waves-effect">
                            <i class="fas fa-shopping-cart"></i>
                            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'logout' %}?next={{ request.path }}">
                            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
                        </a>
                    </li>


                {% else %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'login' %}?next={{ request.path }}">
                            <span class="clearfix d-none d-sm-inline-block"> Login </span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>