Petopia/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from PetopiaApp.views import SignUpView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('PetopiaApp.urls', namespace='PetopiaApp')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PetopiaApp/urls.py
from django.urls import path
from PetopiaApp.views import home, add_pet_category, shopping_cart, add_to_cart, \
    remove_from_cart, product, remove_one_item_from_cart, checkout, add_product, payment, orders
from django.conf import settings
from django.conf.urls.static import static

app_name = 'PetopiaApp'

urlpatterns = [
    path("", home, name='home'),
    path("<category>", home, name='home'),

    path("add-pet-category/", add_pet_category, name='add_pet_category'),
    path("add-product/", add_product, name='add_product'),

    path('product/<name>/<slug>', product, name='product'),

    path('cart/shopping-cart', shopping_cart, name='shopping_cart'),
    path('add-to-cart/<slug>', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug>', remove_from_cart, name='remove_from_cart'),
    path('remove-one-item-from-cart/<slug>', remove_one_item_from_cart, name='remove_one_item_from_cart'),

    path('checkout/', checkout, name='checkout'),
    path('payment/<payment_option>', payment, name='payment'),
    path('orders/', orders, name='orders')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PetopiaApp/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User

# Create your models here.

PRODUCT_CATEGORIES = (
    ('food', 'food'),
    ('hygiene', 'hygiene'),
    ('toys', 'toys'),
    ('transport', 'transport')
)


class PetCategory(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to="images/pet_images/", null=True, blank=True)

    def __str__(self):
        return f"{self.name}"


class Brand(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    image = models.ImageField(upload_to="images/product_images/", null=True)
    short_description = models.CharField(max_length=255)
    detailed_description = models.TextField()
    pet_category = models.ForeignKey(PetCategory, on_delete=models.CASCADE)
    product_category = models.CharField(max_length=10, choices=PRODUCT_CATEGORIES)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    slug = models.SlugField()

    def __str__(self):
        return f"{self.name} - ${self.price}"

    def get_absolute_url(self):
        return reverse("PetopiaApp:product", kwargs={
            'slug': self.slug,
            'name': self.pet_category
        })


class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} x {self.product}"

    def get_total_cart_item_price(self):
        return self.quantity * self.product.price


class ShoppingCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(CartItem)

    def __str__(self):
        return f"{self.user.username}"

    def get_total(self):
        total = 0
        for cart_item in self.items.all():
            total += cart_item.get_total_cart_item_price()
        return total

    def get_total_num_items(self):
        total = 0
        for cart_item in self.items.all():
            total += cart_item.quantity
        return total

PetopiaApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from PetopiaApp.models import PetCategory, Product
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


class PetCategoryForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(PetCategoryForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = PetCategory
        fields = ["name", ]


class ProductForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Product
        fields = ["name", "price", "image", "short_description", "detailed_description", "pet_category",
                  "product_category", "brand", "slug"]


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)


class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': '1234 Main St'
    }))
    apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Apartment or suite'
    }))
    country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(
        attrs={'class': 'custom-select d-block w-100'})
    )
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    same_shipping_address = forms.BooleanField(required=False)
    save_info = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

PetopiaApp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404

from PetopiaApp.filters import ProductFilter
from PetopiaApp.forms import PetCategoryForm, CheckoutForm, ProductForm
from PetopiaApp.models import Product, PetCategory, ShoppingCart, CartItem
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.utils import timezone
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.db.models import Q


# Create your views here.

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


def home(request, category=None):
    all_products = Product.objects.all()
    search_query = request.GET.get('search_query')
    if category is not None and request.GET.get('search_query') is None:
        all_products = Product.objects.filter(pet_category=category).all()
    elif (category is None or category is not None) and request.GET.get('search_query') is not None:
        all_products = Product.objects.filter(Q(name__icontains=search_query) |
                                              Q(short_description__icontains=search_query)).all()

    pet_categories = PetCategory.objects.all()
    filter_form = ProductFilter(request.GET, queryset=all_products)

    p = Paginator(all_products, 8)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)

    all_products = page_obj

    context = {'products': all_products, 'pet_categories': pet_categories, 'filter': filter_form}
    return render(request, "home.html", context)


@login_required(login_url="/accounts/login/?next=/")
def add_pet_category(request):
    if request.method == "POST":
        form_data = PetCategoryForm(data=request.POST, files=request.FILES)
        if form_data.is_valid():
            pet_category = form_data.save(commit=False)
            pet_category.save()
            return redirect("PetopiaApp:home")
    return render(request, "admin-actions/add_pet_category.html", context={"form": PetCategoryForm})


@login_required(login_url="/accounts/login/?next=/")
def add_product(request):
    if request.method == "POST":
        form_data = ProductForm(data=request.POST, files=request.FILES)
        if form_data.is_valid():
            print('form data is valid')
            product_obj = form_data.save(commit=False)
            product_obj.name = form_data.cleaned_data.get('name')
            product_obj.price = form_data.cleaned_data.get('price')
            product_obj.image = form_data.cleaned_data.get('image')
            product_obj.short_description = form_data.cleaned_data.get('short_description')
            product_obj.detailed_description = form_data.cleaned_data.get('detailed_description')
            product_obj.pet_category = form_data.cleaned_data.get('pet_category')
            product_obj.product_category = form_data.cleaned_data.get('product_category')
            product_obj.brand = form_data.cleaned_data.get('brand')
            product_obj.slug = form_data.cleaned_data.get('slug')
            product_obj.save()
            return redirect("PetopiaApp:home")
    return render(request, "admin-actions/add_product.html", context={"form": ProductForm})


def product(request, name, slug):
    product_object = Product.objects.filter(slug=slug)[0]
    context = {'object': product_object, 'pet_category': name}
    return render(request, "product.html", context)


@login_required(login_url="/accounts/login/?next=/")
def shopping_cart(request):
    try:
        cart = ShoppingCart.objects.get(user=request.user, ordered=False)
    except ObjectDoesNotExist:
        date_ordered = timezone.now()
        cart = ShoppingCart.objects.create(user=request.user, date_ordered=date_ordered)
    context = {'object': cart}
    return render(request, "cart/shopping_cart.html", context)


@login_required(login_url="/accounts/login/?next=/")
def add_to_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    cart_item, created = CartItem.objects.get_or_create(
        product=product,
        user=request.user,
        ordered=False)
    cart_qs = ShoppingCart.objects.filter(user=request.user, ordered=False)
    if cart_qs.exists():
        cart = cart_qs[0]
        if cart.items.filter(product__slug=product.slug).exists():
            cart_item.quantity += 1
            cart_item.save()
            messages.info(request, "The item quantity was increased!")
            return redirect("PetopiaApp:shopping_cart")
        else:
            messages.info(request, "This item was added to your cart!")
            cart.items.add(cart_item)
            return redirect("PetopiaApp:shopping_cart")
    else:
        date_ordered = timezone.now()
        cart = ShoppingCart.objects.create(user=request.user, date_ordered=date_ordered)
        cart.items.add(cart_item)
        messages.info(request, "This item was added to your cart!")
        return redirect("PetopiaApp:shopping_cart")


@login_required(login_url="/accounts/login/?next=/")
def remove_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = ShoppingCart.objects.filter(
        user=request.user,
        ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(product__slug=product.slug).exists():
            order_item = CartItem.objects.filter(
                product=product,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            messages.info(request, "The item was removed from your cart!")
            return redirect("PetopiaApp:shopping_cart")
        else:
            messages.info(request, "This item was not in your cart!")
            return redirect("PetopiaApp:product", slug=slug)
    else:
        messages.info(request, "You do not have an active shopping cart.")
        return redirect("PetopiaApp:product", slug=slug)


@login_required(login_url="/accounts/login/?next=/")
def remove_one_item_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = ShoppingCart.objects.filter(
        user=request.user,
        ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(product__slug=product.slug).exists():
            order_item = CartItem.objects.filter(
                product=product,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "The item quantity was decreased.")
            return redirect("PetopiaApp:shopping_cart")
        else:
            messages.info(request, "This item was not in your cart!")
            return redirect("PetopiaApp:product", slug=slug)
    else:
        messages.info(request, "You do not have an active shopping cart.")
        return redirect("PetopiaApp:product", slug=slug)


@login_required(login_url="/accounts/login/?next=/")
def checkout(request):
    if request.method == 'GET':
        form = CheckoutForm()
        cart = ShoppingCart.objects.get(user=request.user, ordered=False)
        context = {'form': form, 'object': cart}
        return render(request, 'cart/checkout.html', context)
    if request.method == "POST":
        form = CheckoutForm(data=request.POST)
        try:
            cart = ShoppingCart.objects.get(user=request.user, ordered=False)
            if form.is_valid():
                payment_option = form.cleaned_data.get('payment_option')
                cart.save()
                if payment_option == 'S':
                    return redirect('PetopiaApp:payment', payment_option='stripe')
                elif payment_option == 'P':
                    return redirect('PetopiaApp:payment', payment_option='paypal')
            else:
                messages.warning(request, "Failed Checkout")
                return render(request, 'cart/checkout.html', {'form': form})
        except ObjectDoesNotExist:
            messages.error(request, "You do not have an active shopping cart!")
            return redirect("PetopiaApp:shopping_cart")


@login_required(login_url="/accounts/login/?next=/")
def payment(request, payment_option):
    if request.method == "GET":
        cart = ShoppingCart.objects.get(user=request.user, ordered=False)
        context = {'payment_option': payment_option, 'object': cart}
        return render(request, "cart/payment.html", context)
    if request.method == "POST":
        cart = ShoppingCart.objects.get(user=request.user, ordered=False)
        cart.ordered = True
        cart.date_ordered = timezone.now()
        cart.save()
        messages.success(request, "Your order was successful!")
        return redirect("PetopiaApp:home")


@login_required(login_url="/accounts/login/?next=/")
def orders(request):
    query = ShoppingCart.objects.filter(user=request.user, ordered=True)
    context = {'orders': query}
    return render(request, "cart/orders.html", context)

PetopiaApp/templates/cart/checkout.html
{% extends "base.html" %}
{% load cart_template_tags %}

{% block content %}

    <main class="pt-4">
        <div class="container wow fadeIn">

            <div style="width: 20%">
                <a href="{% url 'PetopiaApp:shopping_cart' %}" class="btn text-white btn-md btn-block" type="submit"
                   style="background-color: #717171">
                    Back to Shopping Cart</a>
            </div>

            <h2 class="my-5 h2 text-center">Checkout form</h2>

            <div class="row">
                <div class="col-md-8 mb-2 mt-2">
                    <div class="card">
                        <form class="card-body" method="POST">
                            {% csrf_token %}

                            <div class="row">
                                <!--address-->
                                <div class="md-form mb-5 col-lg-4">
                                    <label for="address" class="ml-3">Address</label>
                                    {{ form.street_address }}
                                </div>
                                <!--address-2-->
                                <div class="md-form mb-5 col-lg-4">
                                    <label for="address-2" class="ml-3">Address 2 (optional)</label>
                                    {{ form.apartment_address }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-4 col-md-12 mb-4">
                                    <label for="country">Country</label>
                                    {{ form.country }}
                                    <div class="invalid-feedback">
                                        Please select a valid country.
                                    </div>
                                </div>

                                <div class="col-lg-4 col-md-6 mb-4">
                                    <label for="zip">Zip</label>
                                    {{ form.zip }}
                                    <div class="invalid-feedback">
                                        Zip code required.
                                    </div>
                                </div>

                            </div>

                            <hr>

                            <div class="d-block my-3">
                                {% for value, name in form.fields.payment_option.choices %}

                                    <div class="custom-control custom-radio">
                                        <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio"
                                               class="custom-control-input" required>
                                        <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                                    </div>
                                {% endfor %}
                            </div>

                            <hr class="mb-4">
                            <button class="btn text-white btn-lg btn-block" type="submit"
                                    style="background-color: #0A3E09">Continue to payment
                            </button>

                        </form>
                    </div>

                </div>
                <div class="col-md-4 mb-4">

                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Your order</span>
                        <span class="badge badge-danger badge-pill">{{ request.user|cart_item_count }}</span>
                    </h4>

                    <ul class="list-group mb-3 z-depth-1">
                        {% for item in object.items.all %}
                            <li class="list-group-item d-flex justify-content-between lh-condensed">
                                <div>
                                    <h6 class="my-0">
                                        <span class="text-muted">{{ item.quantity }} x</span>
                                        {{ item.product.name }}
                                    </h6>
                                    <small class="text-muted">{{ item.product.short_description }}</small>
                                </div>
                                <span class="text-muted">${{ item.product.price }}</span>
                                <span class="text-muted">
                                    <b>${{ item.get_total_cart_item_price }}</b>
                                </span>
                            </li>
                        {% endfor %}

                        <li class="list-group-item d-flex justify-content-between">
                            <span>Total (USD)</span>
                            <strong>${{ object.get_total }}</strong>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
    </main>

{% endblock content %}

PetopiaApp/templates/cart/orders.html
{% extends "base.html" %}

{% block content %}

    <div class="container mx-auto text-center col-6 pt-5 mb-5">
        <div class="card mb-3">
            <div class="card-header">
                <h3 class="card-title mt-2">
                    <b>Your orders</b>
                </h3>
            </div>
            <div class="card-body text-left">
                {% for order in orders %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <h6 class="card-subtitle mb-2">Ordered on: {{ order.date_ordered }}</h6>
                            {% for item in order.items.all %}
                                <p class="card-text">{{ item }}</p>
                            {% endfor %}
                        </div>
                        <div class="card-footer d-flex justify-content-between">
                            <span>Total (USD)</span>
                            <strong>${{ order.get_total }}</strong>
                        </div>
                    </div>
                {% empty %}
                    <div class="mb-3 text-center">
                        <div class="card-body">
                            <h6 class="mb-2 pt-4 pb-4">You don't have any orders!</h6>

                            <a href="{% url 'PetopiaApp:home' %}" class="text-dark btn btn-lg">
                                Browse Products
                                <i class="fas fa-paw ml-2"></i>
                            </a>
                        </div>
                    </div>

                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

PetopiaApp/templates/cart/payment.html
{% extends "base.html" %}
{% load cart_template_tags %}

{% block content %}

    <main class="pt-4">
        <div class="container wow fadeIn mb-5">

            <div style="width: 20%">
                <a href="{% url 'PetopiaApp:checkout' %}" class="btn text-white btn-md btn-block" type="submit"
                   style="background-color: #717171">Back to Checkout</a>
            </div>
            <h2 class="my-5 h2 text-center">Payment with {{ payment_option }}</h2>
            <div class="row">
                <div class="col-md-8 mb-4">
                    <div class="card mb-5">
                        <form class="card-body" method="POST">
                            {% csrf_token %}

                            <div class="md-form mb-5" style="width: 65%">
                                <input type="text" maxlength="16" id="card-number" class="form-control" required
                                       placeholder="4242 4242 4242 4242">
                                <label for="card-number" class="">Card Number</label>
                            </div>

                            <div class="row">

                                <div class="col-lg-4 col-md-12 mb-4">

                                    <label for="country">Expiration</label>
                                    <input type="text" maxlength="5" class="custom-select d-block w-100" id="expiration"
                                           required placeholder="12/25">
                                    <div class="invalid-feedback">
                                        Please select a valid expiration date.
                                    </div>
                                </div>

                                <div class="col-lg-4 col-md-6 mb-4">
                                    <label for="zip">CVC</label>
                                    <input type="password" maxlength="3" class="form-control" id="cvc" placeholder="222"
                                           required>

                                    <div class="invalid-feedback">
                                        CVC code required.
                                    </div>

                                </div>

                            </div>

                            <hr class="mb-4 ">
                            <button class="btn text-white btn-lg btn-block mb-5" type="submit"
                                    style="background-color: #0A3E09">Pay
                            </button>

                        </form>

                    </div>

                </div>
                <div class="col-md-4 mb-5">

                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Your cart</span>
                        <span class="badge badge-danger badge-pill">{{ request.user|cart_item_count }}</span>
                    </h4>

                    <ul class="list-group mb-3 z-depth-1">
                        {% for item in object.items.all %}
                            <li class="list-group-item d-flex justify-content-between lh-condensed">
                                <div>
                                    <h6 class="my-0">{{ item.product.name }}</h6>
                                    <small class="text-muted">{{ item.product.short_description }}</small>
                                </div>
                                <span class="text-muted">{{ item.quantity }} x ${{ item.product.price }}</span>
                                <span class="text-muted">
                    <b>${{ item.get_total_cart_item_price }}</b>
                </span>
                            </li>
                        {% endfor %}

                        <li class="list-group-item d-flex justify-content-between">
                            <span>Total (USD)</span>
                            <strong>${{ object.get_total }}</strong>
                        </li>
                    </ul>

                </div>
            </div>

        </div>
    </main>

{% endblock content %}

PetopiaApp/templates/cart/shopping_cart.html
{% extends "base.html" %}

{% block content %}

    <style>
        .th>th {
            font-size: 16px; font-weight: bold
        }
    </style>
    <main>
        <div class="container text-center" style="margin-bottom: 20px">
            <h2 class="pt-5">Your Shopping Cart</h2>
            <hr class="mx-auto opacity-100 w-50 border-12" style="width: 10px; background-color: #292D32">
            <table class="table mb-5 mx-auto">
                <thead class="border bg-white border-1">
                <tr class="th">
                    <th scope="col">Item Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total Price</th>
                    <th scope="col"></th>
                </tr>
                </thead>

                <tbody class="text-white mt-5 table-dark">
                {% for cart_item in object.items.all %}
                    <tr>
                        <td>
                            {{ cart_item.product.name }}
                        </td>
                        <td>${{ cart_item.product.price }}</td>
                        <td>
                            <a class="text-white" href="{% url 'PetopiaApp:remove_one_item_from_cart' cart_item.product.slug %}">-</a>
                            {{ cart_item.quantity }}
                            <a class="text-white" href="{% url 'PetopiaApp:add_to_cart' cart_item.product.slug %}">+</a>
                        </td>
                        <td>${{ cart_item.get_total_cart_item_price }}
                        </td>
                        <td>
                            <a class="btn-sm btn-danger"
                               href="{% url 'PetopiaApp:remove_from_cart' cart_item.product.slug %}">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>

                {% empty %}
                    <tr>
                        <td colspan="5" class="pt-5 pb-5">
                            <b style="font-size: 20px">
                                Your shopping cart is empty!
                            </b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class="btn btn-primary float-left ml-2" href="{% url 'PetopiaApp:home' %}">Shop More</a>
                        </td>
                    </tr>
                {% endfor %}
                {% if object.get_total %}
                    <tr>
                        <td style="font-size: 20px; font-weight: bold"><b>Order Total</b></td>
                        <td></td>
                        <td></td>
                        <td style="font-size: 20px; font-weight: bold"><b>${{ object.get_total }}</b></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class="btn text-white float-left ml-2" href="{% url 'PetopiaApp:home' %}"
                               style="background-color: #717171">Shop More</a>
                            <a class="btn text-white float-right" href="{% url 'PetopiaApp:checkout' %}"
                               style="background-color: #0A3E09">Continue to
                                checkout</a>
                        </td>
                    </tr>
                {% endif %}

                </tbody>
            </table>
        </div>
    </main>

{% endblock %}